services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - quarkusai-network

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - quarkusai-network

  quarkusai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkusai-app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_LANGCHAIN4J_QDRANT_HOST=qdrant
      - QUARKUS_LANGCHAIN4J_OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - qdrant
      - ollama
    networks:
      - quarkusai-network

volumes:
  qdrant_data:
  ollama_data:

networks:
  quarkusai-network:
    driver: bridge
